Further UEFI optimations (#70).

diff --git a/linbofs/usr/bin/linbo_cmd b/linbofs/usr/bin/linbo_cmd
--- a/linbofs/usr/bin/linbo_cmd
+++ b/linbofs/usr/bin/linbo_cmd
@@ -6,7 +6,7 @@
 # ssd/4k/8k support - jonny@bzt.de 06.11.2012 anpassung fuer 2.0.12
 #
 # thomas@linuxmuster.net
-# 20220425
+# 20220501
 # GPL v3
 #
 
@@ -562,13 +562,15 @@ format(){
     echo " OK!"
     # issue 85
     [ -n "$label" -a -n "$UDEVADM" ] && "$UDEVADM" trigger
-    # install linbo and grub in cache
     local cachedev="$(cachedev)"
+    local efipart="$(print_efipart)"
+    # install linbo and grub in cache
     if [ "$cachedev" = "$partition" ]; then
       rm -f /tmp/.gui.done
       rm -f /tmp/.update.done
       rm -f /tmp/.grub-install
       rm -f /tmp/.prepare_grub
+      rm -f /tmp/.repair_efi
       update "$(serverip)" "$cachedev"
       linbo_update_gui
       mk_boot
@@ -583,6 +585,11 @@ format(){
           echo "$FQDN" > /cache/hostname
         fi
       fi
+    fi
+    # clean up efi boot entries
+    if [ "$efipart" = "$partition" ]; then
+      rm -f /tmp/.repair_efi
+      repair_efi "$efipart"
     fi
   else
     echo " Failed!"
@@ -1019,36 +1026,29 @@ repair_efi(){
   [ -e "$doneflag" ] && return 0
   local efipart="$1"
   local efiout="/tmp/efiout"
+  local efipath="/cache/boot/efi"
   local startflag="/tmp/.start"
   local line
   local item
   local FOUND
   local bootnr
-  local winbootimg="/cache/boot/efi/EFI/Microsoft/Boot/bootmgfw.efi"
-  # delete windows boot entries, if efi boot image does not exist
-  efibootmgr | grep ^Boot[0-9] | sort -r > "$efiout" || return 1
-  bootnr="$(grep -i windows /tmp/efiout  | awk -F\* '{ print $1 }' | sed 's|Boot||')"
-  if [ -n "$bootnr" -a ! -e "$winbootimg" ]; then
-    for item in $bootnr; do
-      efibootmgr --bootnum "$bootnr" --delete-bootnum 2>> /tmp/linbo.log 1>> /tmp/linbo.log
-    done
-    efibootmgr | grep ^Boot[0-9] | sort -r > "$efiout"
-  fi
-  # remove redundant entries, keep entries with lower number
-  awk -F\* '{ print $2 }' "$efiout" | sort -u | while read item; do
-    [ -z "$item" ] && continue
-    line=""
-    FOUND=""
-    # delete redundant entries
-    grep "$item" "$efiout" | while read line; do
-      if [ -z "$FOUND" ]; then
-        FOUND="yes"
-        continue
-      else
-        bootnr="$(echo "$line" | awk -F\* '{ print $1 }' | sed 's|Boot||')"
-        efibootmgr --bootnum "$bootnr" --delete-bootnum 2>> /tmp/linbo.log 1>> /tmp/linbo.log || return 1
-      fi
-    done
+  local bootldr
+  # delete invalid boot entries and doubles
+  efibootmgr -v | grep ^Boot[0-9] | sort -r | sed 's|\\|/|g' > "$efiout" || return 1
+  grep "/EFI/" "$efiout" | while read line; do
+    bootldr="$(echo "$line" | awk -F\( '{print $3}' | awk -F\) '{print $1}')"
+    bootnr="$(echo "$line" | awk -F\* '{ print $1 }' | sed 's|Boot||')"
+    # remove double entry
+    if echo "$FOUND" | grep -qw "$bootldr"; then
+      efibootmgr -B -b "$bootnr"
+      continue
+    fi
+    # remove invalid entry
+    if [ ! -e "${efipath}${bootldr}" ]; then
+      efibootmgr -B -b "$bootnr"
+      continue
+    fi
+    FOUND="$FOUND $bootldr"
   done
   # create grub entry if missing
   create_efiboot grub "$efipart" || return 1
@@ -1288,6 +1288,7 @@ mk_boot(){
   local APPEND="$4"
   local efipart="$(print_efipart)"
   local partition="$1"
+  local nonv
   remote_cache "$(cachedev)" || local localcache="yes"
   # get disk for grub install, use always the first disk from start.conf
   local grubdisk="$(get_disk_from_partition $(grep -iw ^dev /start.conf | awk -F\= '{ print $2 }' | awk '{ print $1 }' | grep ^/dev | sort -u | head -1))"
@@ -1300,6 +1301,7 @@ mk_boot(){
     mkdir -p /cache/boot/efi
     mount "$efipart" /cache/boot/efi || return 1
     mkdir -p /cache/boot/efi/EFI
+    nonv="--no-nvram"
   fi
   # needed grub dirs
   local grubdir="/cache/boot/grub"
@@ -1318,7 +1320,7 @@ mk_boot(){
   # install grub in mbr/efi
   if [ ! -e "$doneflag" -a -n "$localcache" ]; then
     echo -n "Installing GRUB in MBR/EFI of $grubdisk ... "
-    grub-install --root-directory=/cache -s $grubdisk 2>> /tmp/linbo.log || RC="1"
+    grub-install -s $nonv --root-directory=/cache -s $grubdisk 2>> /tmp/linbo.log || RC="1"
     if [ "$RC" = "0" ]; then
       touch "$doneflag"
       echo "OK!"
