change filename of linbofs64.lz to linbofs.

diff --git a/linbofs/usr/bin/linbo_update b/linbofs/usr/bin/linbo_update
--- a/linbofs/usr/bin/linbo_update
+++ b/linbofs/usr/bin/linbo_update
@@ -61,24 +61,24 @@ cd /cache
 # download newer linbo/linbofs if applicable and check download
 echo "Looking for LINBO updates."
 # first check md5sum of linbofs
-[ -e linbofs64.lz ] && md5_before="$(md5sum linbofs64.lz | awk '{ print $1 }')"
-[ -e linbofs64.lz.md5 ] && mv linbofs64.lz.md5 linbofs64.lz.md5.bak
-linbo_download linbofs64.lz.md5
-md5_after="$(cat linbofs64.lz.md5 2> /dev/null)"
+[ -e linbofs64 ] && md5_before="$(md5sum linbofs64 | awk '{ print $1 }')"
+[ -e linbofs64.md5 ] && mv linbofs64.md5 linbofs64.md5.bak
+linbo_download linbofs64.md5
+md5_after="$(cat linbofs64.md5 2> /dev/null)"
 if [ -z "$md5_after" ]; then
-  echo "Failed to download linbofs64.lz.md5!" >&2
-  [ -e linbofs64.lz.md5.bak ] && mv linbofs64.lz.md5.bak linbofs64.lz.md5
+  echo "Failed to download linbofs64.md5!" >&2
+  [ -e linbofs64.md5.bak ] && mv linbofs64.md5.bak linbofs64.md5
   exit 1
 fi
-rm -f linbofs64.lz.md5.bak
+rm -f linbofs64.md5.bak
 # if the linbofs checksum differs, download recent versions of linbofs and linbo
 if [ "$md5_before" != "$md5_after" ]; then
   # first linbofs
-  linbo_download linbofs64.lz
+  linbo_download linbofs64
   # verify download
-  md5_current="$(md5sum linbofs64.lz | awk '{ print $1 }')"
+  md5_current="$(md5sum linbofs64 | awk '{ print $1 }')"
   if [ "$md5_current" != "$md5_after" ]; then
-    echo "Checksums differ, failed to download linbofs64.lz!" >&2
+    echo "Checksums differ, failed to download linbofs64!" >&2
     exit 1
   fi
   # second linbo
diff --git a/linbofs/usr/bin/linbo_warmstart b/linbofs/usr/bin/linbo_warmstart
--- a/linbofs/usr/bin/linbo_warmstart
+++ b/linbofs/usr/bin/linbo_warmstart
@@ -2,30 +2,33 @@
 #
 # linbo_warmstart
 # thomas@linuxmuster.net
-# 20230212
+# 20231122
 #
 
 # get environment
 source /usr/share/linbo/shell_functions
 
 # no warmstart in this cases
-if warmstart; then
-  echo "Initiating linbo warmstart ..."
-else
-  echo "Initiating linbo reboot ..."
-  /sbin/reboot -f
+if ! warmstart; then
+  echo "Linbo warmstart is switched off."
   exit 0
 fi
 
 KEXEC="/sbin/kexec"
-KERNEL="linbo64"
-INITRD="linbofs64.lz"
+KERNEL="/cache/linbo64"
+INITRD="/cache/linbofs64"
 
-cd /
-linbo_cmd mountcache || exit 1
+linbo_mountcache || exit 1
+
+if [ ! -s "$KERNEL" -o ! -s "$INITRD" ]; then
+  echo "Linbokernel not found!"
+  exit 1
+fi
+
+echo "Initiating linbo warmstart ..."
 
 # load linbo kernel
-if ! $KEXEC --type="bzImage64" --reuse-cmdline --initrd="/cache/$INITRD" --load "/cache/$KERNEL"; then
+if ! $KEXEC --type="bzImage64" --reuse-cmdline --initrd="$INITRD" --load "$KERNEL"; then
   echo "Failed to load kernel!"
   exit 1
 fi
