implemented client side diff image creation.

diff --git a/linbofs/usr/bin/linbo_cmd b/linbofs/usr/bin/linbo_cmd
--- a/linbofs/usr/bin/linbo_cmd
+++ b/linbofs/usr/bin/linbo_cmd
@@ -473,7 +473,7 @@ mountpart(){
   [ "$3" = "-r" ] && ro=",ro"
   local options
   case "$type" in
-    ntfs) options="-t ntfs3 -o defaults$ro" ;;
+    ntfs) options="-t ntfs3 -o acl,noatime,nls=utf8,discard$ro" ;;
     vfat) options="-i -t $type -o defaults$ro" ;;
     *) options="-i -t $type -o acl,user_xattr$ro" ;;
   esac
@@ -1735,17 +1735,83 @@ prepare_fs(){
 }
 
 
-# mk_qcow2 rootdev imagename
+# mk_baseimage rootdev imagefile
+mk_baseimage(){
+  local rootdev="$1"
+  local imagefile="$2"
+  echo "Filling up partition with zeroes..."
+  # Create nulled files of size 1GB, should work on any FS.
+  local count=0
+  while true; do
+    # tschmitt: log errors to image.log
+    interruptible dd if=/dev/zero of="/mnt/zero$count.tmp" bs=1024k count=1000 || break
+    [ -s "/mnt/zero$count.tmp" ] || break
+    let count++
+    echo "$(du -ch /mnt/zero*.tmp | tail -1 | awk '{ print $1 }') zeroed ... "
+  done
+  # remove excluded files
+  grep -v ^# /etc/rsync.exclude | while read line; do
+    [ -z "$line" ] && continue
+    [ "${line:0:1}" = " " ] && continue
+    rm -rf /mnt/$line
+  done
+  # Sync is asynchronous, unless started twice at least.
+  sync ; sync ; sync
+  rm -f /mnt/zero*.tmp
+  umount /mnt || umount -l /mnt
+  echo "Starting compression of $rootdev -> $imagefile (full partition, ${size}K)."
+  echo "qemu-img convert -p -c -f raw -O qcow2 $rootdev $imagefile"
+  interruptible qemu-img convert -p -c -f raw -O qcow2 "$rootdev" "$imagefile" ; RC="$?"
+  if [ "$RC" != "0" ]; then
+    echo "Creation of $imagefile failed. :("
+    return "$RC"
+  fi
+  # remove diffimage files in case of new baseimage
+  rm -f "${imagefile/.qcow2/.qdiff}"*
+}
+
+
+# mk_diffimage rootdev imagefile
+mk_diffimage(){
+  local rootdev="$1"
+  local imagefile="$2"
+  # create imagefile if it is not yet there
+  if [ ! -e "$imagefile" ]; then
+    qemu-img create -f qcow2 -b "${imagefile/.qdiff/.qcow2}" "$imagefile" || return 1
+  fi
+  # connect imagefile to nbd device
+  qemu-nbd --disconnect /dev/nbd0
+  qemu-nbd --connect /dev/nbd0 "$imagefile" || return 1
+  mkdir -p /image
+  # mount image filesystem
+  if ! mount /dev/nbd0 /image; then
+    qemu-nbd --disconnect /dev/nbd0
+    return 1
+  fi
+  echo "Start syncing differences of $rootdev -> $imagefile."
+  interruptible rsync -HAa --exclude="/.linbo" --exclude-from="/etc/rsync.exclude" --delete --delete-excluded  /mnt/ /image 2>&1 ; RC="$?"
+  umount /image || umount -l /image
+  qemu-nbd --disconnect /dev/nbd0
+  [ "$RC" = "0" ] && return
+  echo "Creation of $imagefile failed. :("
+  rm -f "$imagefile"*
+  return "$RC"
+}
+
+
+# mk_qcow2 rootdev imagefile
 mk_qcow2(){
   local rootdev="$1"
-  local imagename="$2"
-  echo "## $(date) : Starting creation of $imagename." | tee -a /tmp/image.log
+  local imagefile="$2"
+  local imageext="${imagefile/*.}"
+  [ "$(pwd)" = "/cache" ] || cd /cache
+  echo "## $(date) : Starting creation of $imagefile." | tee -a /tmp/image.log
   # kill torrent process for this image
-  local pid="$(ps w | grep ctorrent | grep "$imagename.torrent" | grep -v grep | awk '{ print $1 }')"
+  local pid="$(ps w | grep ctorrent | grep "$imagefile.torrent" | grep -v grep | awk '{ print $1 }')"
   [ -n "$pid" ] && kill "$pid"
   # remove torrent files
-  [ -e "/cache/$imagename.torrent" ] && rm -f "/cache/$imagename.torrent"
-  [ -e "/cache/$imagename.complete" ] && rm -f "/cache/$imagename.complete"
+  [ -e "/cache/$imagefile.torrent" ] && rm -f "/cache/$imagefile.torrent"
+  [ -e "/cache/$imagefile.complete" ] && rm -f "/cache/$imagefile.complete"
   local RC=1
   local size="$(get_partition_size $rootdev)"
   if [ -z "$size" ]; then
@@ -1767,44 +1833,26 @@ mk_qcow2(){
     echo "Cannot prepare $rootdev!"
     return "$RC"
   fi
-  echo "Filling up partition with zeroes..." | tee -a /tmp/image.log
-  # Create nulled files of size 1GB, should work on any FS.
-  local count=0
-  while true; do
-    # tschmitt: log errors to image.log
-    interruptible dd if=/dev/zero of="/mnt/zero$count.tmp" bs=1024k count=1000 2>>/tmp/image.log || break
-    [ -s "/mnt/zero$count.tmp" ] || break
-    let count++
-    echo "$(du -ch /mnt/zero*.tmp | tail -1 | awk '{ print $1 }') zeroed ... " | tee -a /tmp/image.log
-  done
-  # remove excluded files
-  grep -v ^# /etc/rsync.exclude | while read line; do
-    [ -z "$line" ] && continue
-    [ "${line:0:1}" = " " ] && continue
-    rm -rf /mnt/$line
-  done
-  # Sync is asynchronous, unless started twice at least.
-  sync ; sync ; sync
-  rm -f /mnt/zero*.tmp
-  umount /mnt || umount -l /mnt
-  echo "Starting compression of $rootdev -> $imagefile (full partition, ${size}K)." | tee -a /tmp/image.log
-  echo "qemu-img convert -p -c -f raw -O qcow2 $rootdev $imagefile" | tee -a /tmp/image.log
   set -o pipefail
-  interruptible qemu-img convert -p -c -f raw -O qcow2 "$rootdev" "$imagefile" | tee -a /tmp/image.log ; RC="$?"
-  set +o pipefail
+  case "$imageext" in
+    qcow2) mk_baseimage "$rootdev" "$imagefile" | tee -a /tmp/image.log ; RC="$?" ;;
+    qdiff) mk_diffimage "$rootdev" "$imagefile" | tee -a /tmp/image.log ; RC="$?" ;;
+    *) echo "Unknown image type!" ; RC="1" ;;
+  esac
   if [ "$RC" != "0" ]; then
-    echo "Creation of $imagefile failed. :(" | tee -a /tmp/image.log
+    set +o pipefail
+    umount /mnt || umount -l /mnt
     return "$RC"
   fi
-  set -o pipefail
+  # mount rootdevice after image creation
   mountpart "$rootdev" /mnt -w | tee -a /tmp/image.log ; RC="$?"
   set +o pipefail
   if [ "$RC" != "0" ]; then
     echo "Mounting of $rootdev failed. :(" | tee -a /tmp/image.log
     return "$RC"
   fi
-  local imagename="${imagefile%.qcow2}"
-  echo "$imagename" > /mnt/.linbo
+  # save imagename on partition
+  echo "${imagefile/.*}" > /mnt/.linbo
   umount /mnt || umount -l /mnt
   # create info file
   local imgsize="$(get_filesize $imagefile)"
@@ -1863,7 +1911,7 @@ sync_image(){
     echo "Cannot mount $targetdev!"
     return "$RC"
   fi
-  local ROPTS="-HaAX"
+  local ROPTS="-HAa"
   [ "$(fstype "$targetdev")" = "vfat" ] && ROPTS="-rt"
   # mount qcow2 image as network block device
   set -o pipefail
@@ -2415,23 +2463,33 @@ syncl(){
   return "$RC"
 }
 
-# create cachedev imagefile baseimagefile bootdev rootdev kernel initrd
+# create cachedev imagefile baseimagefile bootdev rootdev kernel initrd (obsolete)
+# create cachedev imagefile rootdev
 create(){
   echo -n "create " ;  printargs "$@" | tee -a /tmp/image.log
-  [ -z "$1" -o -z "$5" ] && return 1
-  [ -z "$2" -a -z "$3" ] && return 1
-  if [ -n "$2" -a -n "$3" ]; then
-    if [ "$2" != "$3" ]; then
-      echo "Differential images are currently not supported!"
-      return 1
-    fi
+  # check parameters
+  if [ -b "$1" ]; then
+    local cachedev="$1"
+  else
+    echo "Given cache device is not a block device!"
+    return 1
   fi
-  local cachedev="$1"
-  local imagefile="$2"
-  local baseimagefile="$3"
-  local rootdev="$5"
-  if ! echo "$imagefile" | grep -q ".qcow2"; then
-    echo "Only the creation of qcow2 images is currently supported!"
+  local imagefile
+  if [ "${2/*.}" = "qcow2" -o "${2/*.}" = "qdiff" ]; then
+    imagefile="$2"
+  elif [ "${3/*.}" = "qcow2" -o "${3/*.}" = "qdiff" ]; then
+    imagefile="$3"
+  else
+    echo "Given imagefile name is not valid!"
+    return 1
+  fi
+  local rootdev
+  if [ -b "$3" ]; then
+    rootdev="$3"
+  elif [ -b "$5" ]; then
+    rootdev="$5"
+  else
+    echo "Given root device is not a block device!"
     return 1
   fi
   mountcache "$cachedev" || return 1
@@ -2445,7 +2503,7 @@ create(){
   local RC="1"
   echo "Creating image $imagefile of partition $rootdev ..." | tee -a /tmp/image.log
   set -o pipefail
-  mk_qcow2 "$rootdev" "$imagefile"  | tee -a /tmp/image.log ; RC="$?"
+  mk_qcow2 "$rootdev" "$imagefile" | tee -a /tmp/image.log ; RC="$?"
   set +o pipefail
   [ "$RC" = "0" ] && echo "Done." || echo "Failed" | tee -a /tmp/image.log
   sendlog
