linbofs: improved logging (#123).

diff --git a/linbofs/usr/bin/linbo_create_image b/linbofs/usr/bin/linbo_create_image
--- a/linbofs/usr/bin/linbo_create_image
+++ b/linbofs/usr/bin/linbo_create_image
@@ -2,7 +2,7 @@
 #
 # linbo_create_image
 # thomas@linuxmuster.net
-# 20250415
+# 20250423
 #
 
 
@@ -80,7 +80,7 @@ prepare_fs(){
       if [ "$(linbo_fstype $2)" = "ntfs" ]; then
         targetdir="$(ls -d [Ee][Ff][Ii]/[Mm][Ii][Cc][Rr][Oo][Ss][Oo][Ff][Tt]/[[Bb][Oo][Oo][Tt] 2> /dev/null)"
         [ -z "$targetdir" ] && targetdir="EFI/Microsoft/Boot"
-        save_efi_bcd "$targetdir" "$efipart" | tee -a /tmp/linbo_image.log
+        save_efi_bcd "$targetdir" "$efipart"
       fi
     else
       targetdir="$(ls -d [Bb][Oo][Oo][Tt] 2> /dev/null)"
@@ -102,11 +102,11 @@ prepare_fs(){
         local bsmbr="$targetdir/bsmbr.$HOSTGROUP"
         # save bootloader sectors
         echo "Saving bootloader sectors for group $HOSTGROUP."
-        dd if="$disk" of="$bsmbr" bs=446 count=1 2>> /tmp/linbo.log
+        dd if="$disk" of="$bsmbr" bs=446 count=1
         # ntfs partition id
         echo "Saving ntfs id."
         local ntfsid="$targetdir/ntfs.id"
-        dd if="$2" of="$ntfsid" bs=8 count=1 skip=9 2>> /tmp/linbo.log
+        dd if="$2" of="$ntfsid" bs=8 count=1 skip=9
       fi
     fi
   )
@@ -117,21 +117,12 @@ prepare_fs(){
 mk_baseimage(){
   local rootdev="$1"
   local imagefile="$2"
-  echo "Filling up partition with zeroes..." | tee -a /tmp/image.log
+  echo "Filling up partition with zeroes..."
   freespace=$(df -kP $rootdev | awk 'NR==2 {print $4}')k
-  interruptible pv -s $freespace -tprebf /dev/zero | dd of=/mnt/zero.tmp bs=1024k 2>/tmp/image.log
+  interruptible pv -s $freespace -tprebf /dev/zero | dd of=/mnt/zero.tmp bs=1024k
 
 
   # Create nulled files of size 1GB, should work on any FS.
-  #local count=0
-  #while true; do
-  #  # tschmitt: log errors to image.log
-  #  interruptible dd if=/dev/zero of="/mnt/zero$count.tmp" bs=1024k count=1000 2>>/tmp/image.log || break
-  #  [ -s "/mnt/zero$count.tmp" ] || break
-  #  let count++
-  #  echo "$(du -ch /mnt/zero*.tmp | tail -1 | awk '{ print $1 }') zeroed ... " | tee -a /tmp/image.log
-  #done
-  # Sync is asynchronous, unless started twice at least.
   sync ; sync ; sync
   rm -f /mnt/zero.tmp
   umount /mnt || umount -l /mnt
@@ -206,7 +197,7 @@ mk_qcow2(){
   local imagefile="$2"
   local imageext="${imagefile/*.}"
   [ "$(pwd)" = "/cache" ] || cd /cache
-  echo "## $(date) : Starting creation of $imagefile." | tee -a /tmp/image.log
+  echo "## $(date) : Starting creation of $imagefile."
   # kill torrent process for this image
   local pid="$(ps w | grep ctorrent | grep "$imagefile.torrent" | grep -v grep | awk '{ print $1 }')"
   [ -n "$pid" ] && kill "$pid"
@@ -216,23 +207,23 @@ mk_qcow2(){
   local RC=1
   local size="$(get_partition_size $rootdev)"
   if [ -z "$size" ]; then
-    echo "Cannot get size of $rootdev!" | tee -a /tmp/image.log
+    echo "Cannot get size of $rootdev!"
     return 1
   fi
-  linbo_mount "$rootdev" /mnt | tee -a /tmp/linbo.log ; RC="$?"
+  linbo_mount "$rootdev" /mnt ; RC="$?"
   if [ "$RC" != "0" ]; then
     echo "Cannot mount $rootdev!"
     return "$RC"
   fi
-  echo "Preparing partition $rootdev (size=${size}K) for compression..." | tee -a /tmp/image.log
-  prepare_fs /mnt "$rootdev" | tee -a /tmp/image.log ; RC="$?"
+  echo "Preparing partition $rootdev (size=${size}K) for compression..."
+  prepare_fs /mnt "$rootdev" ; RC="$?"
   if [ "$RC" != "0" ]; then
     echo "Cannot prepare $rootdev!"
     return "$RC"
   fi
   case "$imageext" in
-    qcow2) mk_baseimage "$rootdev" "$imagefile" | tee -a /tmp/image.log ; RC="$?" ;;
-    qdiff) mk_diffimage "$rootdev" "$imagefile" | tee -a /tmp/image.log ; RC="$?" ;;
+    qcow2) mk_baseimage "$rootdev" "$imagefile" ; RC="$?" ;;
+    qdiff) mk_diffimage "$rootdev" "$imagefile" ; RC="$?" ;;
     *) echo "Unknown image type!" ; RC="1" ;;
   esac
   if [ "$RC" != "0" ]; then
@@ -240,9 +231,9 @@ mk_qcow2(){
     return "$RC"
   fi
   # mount rootdevice after image creation
-  linbo_mount "$rootdev" /mnt | tee -a /tmp/image.log ; RC="$?"
+  linbo_mount "$rootdev" /mnt ; RC="$?"
   if [ "$RC" != "0" ]; then
-    echo "Mounting of $rootdev failed. :(" | tee -a /tmp/image.log
+    echo "Mounting of $rootdev failed. :("
     return "$RC"
   fi
   # save imagename on partition
@@ -251,12 +242,12 @@ mk_qcow2(){
   # create info file
   local imgsize="$(get_filesize $imagefile)"
   linbo_mkinfo "$imagefile" "$rootdev"
-  echo "Done." | tee -a /tmp/image.log
+  echo "Done."
   ls -l "$rootdev"
   touch "$imagefile".complete
   # create torrent file
   linbo_mktorrent "$imagefile" || RC="1"
-  echo "## $(date) : Creation of $imagefile finished." | tee -a /tmp/image.log
+  echo "## $(date) : Creation of $imagefile finished."
   return "$RC"
 }
 
@@ -266,14 +257,15 @@ mk_qcow2(){
 # print help
 [ -z "$1" -o "$1" = "help" ] && usage 0
 
+# get environment
+source /usr/share/linbo/shell_functions
+echo "### $timestamp $(basename "$0") $@ ###"
+
 # start.conf is needed
 if [ ! -s /start.conf ]; then
   echo "Fatal: start.conf not found!"
   exit 1
 fi
-
-# get environment
-source /usr/share/linbo/shell_functions
 
 # check os number option
 if isinteger "$1"; then
@@ -306,17 +298,17 @@ if [ -n "$osnr" ]; then
   fi
 fi
 
-linbo_mountcache || exit 1
+linbo_mountcache &> /dev/null || exit 1
 
 cd /cache
 
-echo "Creating image $imagefile of partition $root ..." | tee -a /tmp/image.log
-mk_qcow2 "$root" "$imagefile" | tee -a /tmp/image.log ; RC="$?"
+echo "Creating image $imagefile of partition $root ..."
+mk_qcow2 "$root" "$imagefile" ; RC="$?"
 
 if [ "$RC" = "0" ]; then
-  echo "Done." | tee -a /tmp/image.log
+  echo "Done."
 else
-  echo "Failed." | tee -a /tmp/image.log
+  echo "Failed."
 fi
 
 sendlog
diff --git a/linbofs/usr/bin/linbo_download b/linbofs/usr/bin/linbo_download
--- a/linbofs/usr/bin/linbo_download
+++ b/linbofs/usr/bin/linbo_download
@@ -2,7 +2,7 @@
 #
 # linbo_download
 # thomas@linuxmuster.net
-# 20240916
+# 20250423
 #
 
 usage(){
@@ -25,6 +25,7 @@ usage(){
 
 # get environment
 source /usr/share/linbo/shell_functions
+echo "### $timestamp $(basename "$0") $@ ###"
 
 # do not execute in localmode
 if localmode; then
@@ -41,17 +42,17 @@ IMPORTANT="$2"
 
 # downloads files from server into current directory
 RC=1
-[ -n "$IMPORTANT" ] && echo "RSYNC Download $LINBOSERVER -> $FILE..." | tee -a /tmp/linbo.log
+[ -n "$IMPORTANT" ] && echo "RSYNC Download $LINBOSERVER -> $FILE ..."
 TARGET="$(basename $FILE)"
 # ensure target dir exists
 [ "${TARGET: -1}" = "/" ] && mkdir -p "$TARGET"
-interruptible rsync --skip-compress="$RSYNC_SKIP_COMPRESS" -HaLz --partial --progress "$LINBOSERVER::linbo/$FILE" "$TARGET" 2>&1 | tee -a /tmp/linbo.log; RC="$?"
+interruptible rsync --skip-compress="$RSYNC_SKIP_COMPRESS" -HaLz --partial --progress "$LINBOSERVER::linbo/$FILE" "$TARGET" &> /dev/null; RC="$?"
 if [ "$RC" != "0" ]; then
   # Delete incomplete/defective/non-existent file (maybe we should check for returncode=23 first?)
-  rm -f "$FILE" 2>/dev/null
+  rm -f "$FILE"
   if [ -n "$IMPORTANT" ]; then
     # Verbose error message if file was important
-    echo "File $FILE could not be downloaded." | tee -a /tmp/linbo.log
+    echo "File $FILE could not be downloaded."
   fi
 fi
 exit "$RC"
diff --git a/linbofs/usr/bin/linbo_sync b/linbofs/usr/bin/linbo_sync
--- a/linbofs/usr/bin/linbo_sync
+++ b/linbofs/usr/bin/linbo_sync
@@ -2,7 +2,7 @@
 #
 # linbo_sync
 # thomas@linuxmuster.net
-# 20250415
+# 20250423
 #
 
 
@@ -30,8 +30,8 @@ check_status(){
   local partition="$1"
   local imagefile="$2"
   local imagebase="${imagefile%%.*}"
-  echo "## $(date) : Check status of $partition using $imagefile." | tee -a /tmp/linbo.log
-  linbo_mount "$1" /mnt -r 2>> /tmp/linbo.log || return $?
+  echo "## $(date) : Check status of $partition using $imagefile."
+  linbo_mount "$1" /mnt -r || return $?
   [ -s /mnt/.linbo ] && case "$(cat /mnt/.linbo 2>/dev/null)" in *$imagebase*) RC=0 ;; esac
   umount /mnt || umount -l /mnt
   return "$RC"
@@ -44,8 +44,8 @@ update_status(){
   local partition="$1"
   local imagefile="$2"
   local imagebase="${imagefile%.*}"
-  echo "## $(date) : Update status of $partition using $imagefile." | tee -a /tmp/linbo.log
-  linbo_mount "$1" /mnt 2>> /tmp/linbo.log || return $?
+  echo "## $(date) : Update status of $partition using $imagefile."
+  linbo_mount "$1" /mnt || return $?
   echo "$imagebase" > /mnt/.linbo
   #sync; sync; sleep 1
   umount /mnt || umount -l /mnt
@@ -56,12 +56,12 @@ update_status(){
 # differential/Synced
 # sync_image imagefile targetdev
 sync_image(){
-  echo "## $(date) : Starting sync of $1 to $2." | tee -a /tmp/image.log
+  echo "## $(date) : Starting sync of $1 to $2."
   local imagefile="$1"
   local targetdev="$2"
   local RC
 
-  linbo_mount "$targetdev" /mnt | tee -a /tmp/image.log ; RC="$?"
+  linbo_mount "$targetdev" /mnt ; RC="$?"
   if [ "$RC" != "0" ]; then
     echo "Cannot mount $targetdev!"
     return "$RC"
@@ -70,10 +70,10 @@ sync_image(){
   local ROPTS="-HAa"
   [ "$(linbo_fstype "$targetdev")" = "vfat" ] && ROPTS="-rt"
   # mount qcow2 image as network block device
-  qemu-nbd -r --connect /dev/nbd0 "$imagefile" | tee -a /tmp/image.log ; RC="$?"
+  qemu-nbd -r --connect /dev/nbd0 "$imagefile" ; RC="$?"
   if [ "$RC" != "0" ]; then
-    echo "Connection to $imagefile failed!" | tee -a /tmp/image.log
-    qemu-nbd --disconnect /dev/nbd0 >> /tmp/image.log
+    echo "Connection to $imagefile failed!"
+    qemu-nbd --disconnect /dev/nbd0
     return "$RC"
   fi
 
@@ -81,24 +81,24 @@ sync_image(){
   sleep 3
   mkdir -p /image
   if ! linbo_mount /dev/nbd0 /image -r; then
-    echo "Mounting $imagefile failed!" | tee -a /tmp/image.log
-    qemu-nbd --disconnect /dev/nbd0 >> /tmp/image.log
+    echo "Mounting $imagefile failed!"
+    qemu-nbd --disconnect /dev/nbd0
     return "$RC"
   fi
 
   # sync image
   echo "Syncing ... please wait ..."
-  interruptible rsync --skip-compress="$RSYNC_SKIP_COMPRESS" "$ROPTS" --exclude="/.linbo" --exclude-from="/etc/rsync.exclude" --delete --delete-excluded --log-file=/tmp/image.log --log-file-format="" /image/ /mnt 2>&1 | tee -a /tmp/image.log ; RC="$?"
+  interruptible rsync --skip-compress="$RSYNC_SKIP_COMPRESS" "$ROPTS" --exclude="/.linbo" --exclude-from="/etc/rsync.exclude" --delete --delete-excluded --log-file=/tmp/linbo.log --log-file-format="" /image/ /mnt ; RC="$?"
   umount /image
   if [ "$RC" != "0" ]; then
-    echo "Image sync of $imagefile to $targetdev failed!" | tee -a /tmp/image.log
+    echo "Image sync of $imagefile to $targetdev failed!"
   fi
-  qemu-nbd --disconnect /dev/nbd0 >> /tmp/image.log
+  qemu-nbd --disconnect /dev/nbd0
 
   sync; sync; sleep 1
   umount /mnt || umount -l /mnt
   [ "$RC" = "0" ] && update_status "$2" "$1"
-  echo "## $(date) : Sync from $1 finished." | tee -a /tmp/image.log
+  echo "## $(date) : Sync from $1 finished."
   return "$RC"
 }
 
@@ -106,7 +106,7 @@ sync_image(){
 # full copy
 # cp_image imagefile targetdev
 cp_image(){
-  echo "## $(date) : Starting full restore of $2 using $1." | tee -a /tmp/image.log
+  echo "## $(date) : Starting full restore of $2 using $1."
   local RC=1
   local imagefile="$1"
   local imagetype="${imagefile##*.}"
@@ -128,20 +128,20 @@ cp_image(){
   local s1="$(get_partition_size /dev/nbd0)"
   local s2="$(get_partition_size $targetdev)"
   if [ "$s1" -gt "$s2" ] 2>/dev/null; then
-    echo "Error: $imagefile (${s1}K) is bigger than partition $targetdev (${s2}K)" >&2 | tee -a /tmp/image.log
-    qemu-nbd --disconnect /dev/nbd0 >> /tmp/image.log
+    echo "Error: $imagefile (${s1}K) is bigger than partition $targetdev (${s2}K)" >&2
+    qemu-nbd --disconnect /dev/nbd0
     return 1
   fi
 
   # restore
-  qemu-nbd --disconnect /dev/nbd0 >> /tmp/image.log
+  qemu-nbd --disconnect /dev/nbd0
   # evaluate sync mode
   case "$RESTOREMODE" in
     dd) sync_cmd="qemu-img dd -f $imagetype -O raw bs=8M if=$imagefile of=$targetdev" ;;
     ooo) sync_cmd="qemu-img convert -W -p -f $imagetype -O raw $imagefile $targetdev" ;;
     *) sync_cmd="qemu-img convert -p -f $imagetype -O raw $imagefile $targetdev" ;;
   esac
-  interruptible $sync_cmd | tee -a /tmp/image.log
+  interruptible $sync_cmd
   RC="$?"
   if [ "$RC" != "0" ]; then
     echo "Restore with $imagefile failed!"
@@ -150,24 +150,24 @@ cp_image(){
 
   # check if resize is necessary
   if [ "$s2" -gt "$s1" ]; then
-    echo "Trying to resize filesystem on $targetdev." | tee -a /tmp/image.log
+    echo "Trying to resize filesystem on $targetdev."
     local fstype="$(fstype_startconf "$targetdev")"
     case "$fstype" in
       ntfs)
-        ntfsfix -bd "$targetdev" | tee -a /tmp/image.log
-        ntfsresize -f "$targetdev" | tee -a /tmp/image.log
-        ntfsfix -bd "$targetdev" | tee -a /tmp/image.log
+        ntfsfix -bd "$targetdev"
+        ntfsresize -f "$targetdev"
+        ntfsfix -bd "$targetdev"
         ;;
       ext4)
-        e2fsck -f "$targetdev" | tee -a /tmp/image.log
-        resize2fs -f "$targetdev" | tee -a /tmp/image.log
+        e2fsck -f "$targetdev"
+        resize2fs -f "$targetdev"
         ;;
       *) ;;
     esac
   fi
 
   update_status "$targetdev" "$imagefile" ; RC="$?"
-  echo "## $(date) : Full restore from $imagefile finished." | tee -a /tmp/image.log
+  echo "## $(date) : Full restore from $imagefile finished."
   return "$RC"
 }
 
@@ -214,7 +214,7 @@ set_guid(){
     echo "Restoring disk UUID $guid of $device."
     echo -e "x\ng\n$guid\nw\nY\n" | gdisk "$device" 2>&1
   else
-    echo "Unknown device $device!" | tee -a /tmp/image.log
+    echo "Unknown device $device!"
     return 1
   fi
   blkid "$device" | grep -qi "$guid" || return 1
@@ -352,7 +352,7 @@ restore(){
   echo "Unpacking: $imagefile -> $targetdev"
   check_status "$targetdev" "$imagefile" || force="force"
   if [ "$force" = "force" ]; then
-    linbo_format "$targetdev" "$fstype" "$label" | tee -a /tmp/linbo.log ; RC="$?"
+    linbo_format "$targetdev" "$fstype" "$label" ; RC="$?"
     if [ "$RC" != "0" ]; then
       echo "Formatting of $targetdev failed!"
       return "$RC"
@@ -405,10 +405,10 @@ syncl(){
   fi
 
   # begin syncing
-  echo "syncl $@" | tee -a /tmp/linbo.log
+  echo "syncl $@"
 
   # mount cache and sync
-  linbo_mountcache || return 1
+  linbo_mountcache &> /dev/null || return 1
   cd /cache
   # start syncing image
   restore "$imagefile" "$rootdev" $force ; RC="$?"
@@ -422,11 +422,11 @@ syncl(){
 
   # mount os partition
   if [ "$RC" = "0" ]; then
-    linbo_mount "$rootdev" /mnt 2>> /tmp/linbo.log ; RC="$?"
+    linbo_mount "$rootdev" /mnt ; RC="$?"
   fi
   # return on error
   if [ "$RC" != "0" ]; then
-    echo "Cannot mount $rootdev!" | tee -a /tmp/linbo.log
+    echo "Cannot mount $rootdev!"
     sendlog
     cd /
     return "$RC"
@@ -456,7 +456,7 @@ syncl(){
   if [ -n "$is_win" ]; then
 
     # do registry patching for windows systems
-    [ -s "$patchfile" ] && linbo_patch_registry "$patchfile" | tee /tmp/patch.log
+    [ -s "$patchfile" ] && linbo_patch_registry "$patchfile"
 
     # manage windows boot files
     local bcd_backup
@@ -497,16 +497,16 @@ syncl(){
     [ -e "$bsmbr" ] || bsmbr="$bootdir"/winmbr."$HOSTGROUP"
     [ -e "$bsmbr" ] || bsmbr="$bootdir"/win7mbr."$HOSTGROUP"
     if [ -e "$bsmbr" ]; then
-      echo "Restoring windows bootloader from $(basename "$bsmbr")" | tee -a /tmp/linbo.log
+      echo "Restoring windows bootloader from $(basename "$bsmbr")"
       case "$bsmbr" in
         *bsmbr.*)
-          dd if="$bsmbr" of="$disk" bs=446 count=1 2>> /tmp/linbo.log
+          dd if="$bsmbr" of="$disk" bs=446 count=1
           ;;
         *winmbr.*)
-          dd if="$bsmbr" of="$disk" bs=1 count=4 seek=440 2>> /tmp/linbo.log
+          dd if="$bsmbr" of="$disk" bs=1 count=4 seek=440
           ;;
         *win7mbr.*)
-          dd if="$bsmbr" of="$disk" bs=1 count=4 skip=440 2>> /tmp/linbo.log
+          dd if="$bsmbr" of="$disk" bs=1 count=4 skip=440
           ;;
       esac
     fi
@@ -519,13 +519,13 @@ syncl(){
       if [ -s "$gptlabel" -a ! -s /mnt/.guid.disk ]; then
         echo "Saving current gpt label."
         local gptcurrent="/tmp/gptlabel.current"
-        dd if="$disk" of="$gptcurrent" bs=512 count=34 2>> /tmp/linbo.log
-        echo "Restoring old gpt label from $(basename "$gptlabel")." | tee -a /tmp/linbo.log
-        dd if="$gptlabel" of="$disk" bs=512 count=34 2>> /tmp/linbo.log
+        dd if="$disk" of="$gptcurrent" bs=512 count=34
+        echo "Restoring old gpt label from $(basename "$gptlabel")."
+        dd if="$gptlabel" of="$disk" bs=512 count=34
         # get disk uuid from old gpt label
         print_guid "$disk" > /mnt/.guid.disk
-        echo "Restoring current gpt label." | tee -a /tmp/linbo.log
-        dd if="$gptcurrent" of="$disk" bs=512 count=34 2>> /tmp/linbo.log
+        echo "Restoring current gpt label."
+        dd if="$gptcurrent" of="$disk" bs=512 count=34
       fi
       # move old guid file for os partition in place
       [ ! -s /mnt/.guid.part -a -s "/mnt/.guid.$partname" ] && mv "/mnt/.guid.$partname" /mnt/.guid.part
@@ -537,7 +537,7 @@ syncl(){
           part) device="$rootdev" ;;
         esac
         guidfile="/mnt/.guid.$i"
-        [ -s "$guidfile" ] && set_guid "$device" "$(cat "$guidfile")" | tee -a /tmp/image.log
+        [ -s "$guidfile" ] && set_guid "$device" "$(cat "$guidfile")"
       done
     fi
 
@@ -545,7 +545,7 @@ syncl(){
     [ -e "$bootdir"/ntfs.id ] && local ntfsid="$(ls "$bootdir"/ntfs.id 2> /dev/null)"
     if [ -n "$ntfsid" -a -s "$ntfsid" ]; then
       echo "Restoring ntfs-id $(basename "$ntfsid")."
-      dd if="$ntfsid" of="$rootdev" bs=8 count=1 seek=9 2>> /tmp/linbo.log
+      dd if="$ntfsid" of="$rootdev" bs=8 count=1 seek=9
     fi
 
     # update linuxmuster-win scripts and restore windows activation
@@ -638,15 +638,15 @@ syncr(){
   if remote_cache "$cache"; then
     echo "Cache $cache is not local, skipping remote image update."
   else
-    linbo_mountcache || return 1
+    linbo_mountcache &> /dev/null || return 1
     cd /cache
 
     # try to download baseimage
-    linbo_download_image "$imagefile" || return 1
+    linbo_download_image "$imagefile" &> /dev/null || return 1
 
     # try to download corresponding diff image if there is one
     # remove local diff image if the server does not provide one
-    linbo_download_image "$imagediff" || rm -f "$imagediff"*
+    linbo_download_image "$imagediff" &> /dev/null || rm -f "$imagediff"*
 
     sendlog
     cd /
@@ -661,6 +661,7 @@ syncr(){
 
 # get environment
 source /usr/share/linbo/shell_functions
+echo "### $timestamp $(basename "$0") $@ ###"
 
 # check parameters
 if isinteger "$1"; then
diff --git a/linbofs/usr/bin/linbo_upload b/linbofs/usr/bin/linbo_upload
--- a/linbofs/usr/bin/linbo_upload
+++ b/linbofs/usr/bin/linbo_upload
@@ -2,7 +2,7 @@
 #
 # linbo_upload
 # thomas@linuxmuster.net
-# 20220609
+# 20250423
 #
 
 usage(){
@@ -39,13 +39,9 @@ export RSYNC_PASSWORD="$1" ; shift
 [ -z "$1" -o -b "$1" ] && shift
 FILE="$1"
 
-if remote_cache "$cache"; then
-  echo "Cache $cache is not local, no upload for $FILE." | tee -a /tmp/linbo.log
-  sendlog
-  exit 1
-fi
+echo "### $timestamp $(basename "$0") $FILE ###"
 
-linbo_mountcache || exit 1
+linbo_mountcache &> /dev/null || exit 1
 cd /cache
 
 RC="0"
@@ -61,7 +57,7 @@ if [ -e "$FILE" ]; then
       [ -s "${FILE}.${item}" ] && filelist="$filelist ${FILE}.${item}"
     done
   fi
-  echo "Uploading $filelist to $LINBOSERVER ..." | tee -a /tmp/linbo.log
+  echo "Uploading $filelist to $LINBOSERVER ..."
   for item in $filelist; do
     interruptible rsync --skip-compress="$RSYNC_SKIP_COMPRESS" --log-file=/tmp/rsync.log --progress -Ha $RSYNC_PERMISSIONS --partial "$item" "$LINBOUSER@$LINBOSERVER::linbo-upload/${subdir}${item}"
     # because return code is always 0 this is necessary
@@ -72,13 +68,13 @@ if [ -e "$FILE" ]; then
   done
 else
   RC=1
-  echo "File $FILE does not exist." | tee -a /tmp/linbo.log
+  echo "File $FILE does not exist."
 fi
 
 if [ "$RC" = "0" ]; then
-  echo "Successfully uploaded $filelist to $LINBOSERVER." | tee -a /tmp/linbo.log
+  echo "Successfully uploaded $filelist to $LINBOSERVER."
 else
-  echo "Failed to upload $filelist to $LINBOSERVER." | tee -a /tmp/linbo.log
+  echo "Failed to upload $filelist to $LINBOSERVER."
 fi
 
 cd /
