linbo-torrent improvements, added create and check commands.

diff --git a/serverfs/usr/sbin/linbo-torrent b/serverfs/usr/sbin/linbo-torrent
--- a/serverfs/usr/sbin/linbo-torrent
+++ b/serverfs/usr/sbin/linbo-torrent
@@ -2,7 +2,7 @@
 #
 # starts screen process for each valid torrent in LINBODIR
 # thomas@linuxmuster.net
-# 20210516
+# 20210517
 #
 
 # read environment
@@ -13,29 +13,52 @@ THELPER=$LINBOSHAREDIR/linbo-torrenthelper.sh
 # change to LINBODIR
 cd $LINBODIR
 
-# torrentfile to process (optional, used on upload, default is all were processed)
+# help message
+usage(){
+  echo
+  echo "Usage: $0 <start|stop|restart|reload|status|create|check> [torrent_file]"
+  echo
+  echo "Note:"
+  echo " * The commands start, stop and restart may have optionally a torrent file"
+  echo "   as parameter. So the command is only processed to this certain file."
+  echo " * A torrent file parameter is mandatory with the commands create and check."
+  echo
+  exit 1
+}
+
+# check if torrent file is given
 if [ -n "$2" ]; then
-  if [ "$1" = "create" ]; then
-    if [ "${2##*.}" != "torrent" ]; then
-      echo "$2 is not a torrent file!"
-      exit 1
-    fi
-    if [ -e "$2" ]; then
-      echo "$2 exists already!"
-      exit 1
-    fi
-    image="${2/.torrent/}"
-    if [ ! -s "$image" ]; then
-      echo "Corresponding image file is missing!"
-      exit 1
-    fi
-  elif [ ! -s "$2" -o "${2##*.}" != "torrent" ]; then
+  # torrent file must have the correct extension
+  if [ "${2##*.}" != "torrent" ]; then
     echo "$2 is not a torrent file!"
-    exit 1
+    usage
+  fi
+  # corresponding image file must exist
+  image="${2/.torrent/}"
+  if [ ! -s "$image" ]; then
+    echo "Image file is missing!"
+    usage
   fi
   case "$1" in
-    start|stop|restart|create) ;;
-    *) echo "Option $1 not allowed with torrentfile." ; exit 1 ;;
+    create)
+      # in case of create the torrent file and may not already exist
+      if [ -e "$2" ]; then
+        echo "$2 exists already!"
+        usage
+      fi
+      ;;
+    start|stop|restart|check)
+      # torrent file must exist
+      if [ ! -s "$2" ]; then
+        echo "$2 does not exist!"
+        usage
+      fi
+      ;;
+    reload|status)
+      echo "Command $1 with torrent file is not supported!"
+      usage
+      ;;
+    *) ;;
   esac
   TORRENTS="$2"
 else
@@ -47,7 +70,7 @@ if [ -z "$TORRENTS" ]; then
 fi
 
 # check for torrent screen and return pid
-check_torrent(){
+torrent_pid(){
   local torrent="$1"
   local process="$(screen -ls | grep -w $torrent)"
   [ -z "$process" ] && return 0
@@ -58,10 +81,10 @@ check_torrent(){
 # killing torrent screen
 kill_torrent(){
   local torrent="$1"
-  local pid="$(check_torrent "$torrent")"
+  local pid="$(torrent_pid "$torrent")"
   [ -z "$pid" ] && return 0
   kill "$pid"
-  pid="$(check_torrent "$torrent")"
+  pid="$(torrent_pid "$torrent")"
   if [ -z "$pid" ]; then
     echo "Screen process for $torrent terminated. "
     return 0
@@ -98,28 +121,39 @@ reload(){
   done
 }
 
+# check torrent
+check(){
+  local torrent="$TORRENTS"
+  echo "Checking $torrent ..."
+  if ctorrent -c "$torrent"; then
+    echo "Ok!"
+  else
+    echo "Failed!"
+    exit 1
+  fi
+}
+
 # creates torrent files
 create(){
-  local torrent
+  local torrent="$TORRENTS"
   local pid
   local image
-  for torrent in $TORRENTS; do
-    # skip already running torrents
-    pid="$(check_torrent "$torrent")"
-    if [ -n "$pid" ]; then
-      echo "$torrent is already running."
-      continue
+  # skip already running torrents
+  pid="$(torrent_pid "$torrent")"
+  if [ -n "$pid" ]; then
+    echo "$torrent is already running."
+    return 1
+  else
+    echo "Creating $torrent ..."
+    image="${torrent/.torrent/}"
+    if ctorrent -t -u "http://$serverip:6969/announce" -s "$torrent" "$image" ; then
+      echo "Ok!"
+      linbo-torrent start "$torrent"
     else
-      echo "Creating $torrent ... "
-      image="${torrent/.torrent/}"
-      if create_torrent "$image" ; then
-        echo "Ok!"
-        linbo-torrent restart "$torrent"
-      else
-        echo "Failed!"
-      fi
+      echo "Failed!"
+      exit 1
     fi
-  done
+  fi
 }
 
 # starts torrent screen processes
@@ -128,7 +162,7 @@ start(){
   local pid
   for torrent in $TORRENTS; do
     # skip already running torrents
-    pid="$(check_torrent "$torrent")"
+    pid="$(torrent_pid "$torrent")"
     if [ -n "$pid" ]; then
       echo "$torrent is already running."
       continue
@@ -136,7 +170,7 @@ start(){
       echo -n "Starting screen process for $torrent ... "
       screen -dmS "$torrent" "$THELPER" "$torrent"
       sleep 1
-      pid="$(check_torrent "$torrent")"
+      pid="$(torrent_pid "$torrent")"
       if [ -n "$pid" ]; then
         echo "$pid ... Ok!"
       else
@@ -160,16 +194,12 @@ status(){
 case "$1" in
   start) start ;;
   stop) stop ;;
-  restart)
-    stop
-    start ;;
+  restart) stop ; start ;;
   reload) reload ;;
   status) status ;;
   create) create ;;
-  *)
-    echo "Usage: $0 {start|stop|restart|reload|status|create}"
-    echo "Optionally a torrentfile can be given as second option (start|stop|restart|create only)."
-    exit 1 ;;
+  check) check ;;
+  *) usage ;;
 esac
 
 exit 0
