change linbofs compression to xz.

diff --git a/serverfs/usr/sbin/update-linbofs b/serverfs/usr/sbin/update-linbofs
--- a/serverfs/usr/sbin/update-linbofs
+++ b/serverfs/usr/sbin/update-linbofs
@@ -6,14 +6,14 @@
 #
 # thomas@linuxmuster.net
 # GPL V3
-# 20231116
+# 20231121
 #
 
 # read linuxmuster environment
 source /usr/share/linuxmuster/linbo/helperfunctions.sh || exit 1
 
-if [ ! -e "$SETUPINI" ]; then
-	echo "linuxmuster.net is not configured! Aborting!"
+if [ ! -s "$SETUPINI" ]; then
+	echo "linuxmuster.net is not yet set up, aborting!"
 	exit 0
 fi
 
@@ -28,7 +28,6 @@ if [ -e "$locker" ]; then
 fi
 touch $locker || exit 1
 chmod 400 "$locker"
-curdir=`pwd`
 
 # get kernel image, modules and version
 # first set custom kernel, if provided
@@ -80,7 +79,6 @@ fi
 # clean tmpdir and exit with error
 bailout() {
 	echo "$1"
-	cd "$curdir"
 	[ -n "$locker" -a -e "$locker" ] && rm -f "$locker"
 	exit 1
 }
@@ -107,10 +105,10 @@ exec_hooks() {
 
 create_linbofs() {
 	local linbofs="linbofs64"
-	local linbofs_cpio="$LINBOVARDIR/${linbofs}.cpio"
+	local linbofs_template="$LINBOVARDIR/${linbofs}.xz"
 	local linbofs_cache="$LINBOCACHEDIR/$linbofs"
-	local linbofs_lz="$LINBODIR/${linbofs}.lz"
-	local linbofs_md5="${linbofs_lz}.md5"
+	local linbofs_xz="$LINBODIR/${linbofs}"
+	local linbofs_md5="${linbofs_xz}.md5"
 	local conf
 	local fw_base="/lib/firmware"
 	local fw_dir
@@ -129,9 +127,9 @@ create_linbofs() {
 	mkdir -p "$linbofs_cache"
 	cd "$linbofs_cache" || bailout "Failed to change to $linbofs_cache!"
 	set -o pipefail
-	cat "$linbofs_cpio" | cpio -i -d -H newc --no-absolute-filenames &> /dev/null ; RC="$?"
+	xzcat "$linbofs_template" | cpio -i -d -H newc --no-absolute-filenames &> /dev/null ; RC="$?"
 	set +o pipefail
-	[ "$RC" = "0" ] || bailout " Failed to unpack $(basename "$linbofs_cpio")!"
+	[ "$RC" = "0" ] || bailout " Failed to unpack $(basename "$linbofs_template")!"
 
 	# provide modules
 	echo "Using $KTYPE kernel version $KVERS ..."
@@ -167,14 +165,14 @@ create_linbofs() {
 	touch var/log/lastlog
 	# check and repair permissions
 	for i in .ssh .ssh/authorized_keys; do
-	perms="$(LANG=C stat "$i" | grep ^Access | grep Uid: | awk -F\( '{ print $2 }' | awk -F\/ '{ print $1 }')"
-	if [ "${perms:1:3}" = "666" -o "${perms:1:3}" = "777" ]; then
-		echo "WARNING! $i has bogus permissions!"
-		sleep 3
-		echo "Repairing for now but check your filesystem!"
-		[ -d "$i" ] && chmod 755 "$i"
-		[ -f "$i" ] && chmod 644 "$i"
-	fi
+		perms="$(LANG=C stat "$i" | grep ^Access | grep Uid: | awk -F\( '{ print $2 }' | awk -F\/ '{ print $1 }')"
+		if [ "${perms:1:3}" = "666" -o "${perms:1:3}" = "777" ]; then
+			echo "WARNING! $i has bogus permissions!"
+			sleep 3
+			echo "Repairing for now but check your filesystem!"
+			[ -d "$i" ] && chmod 755 "$i"
+			[ -f "$i" ] && chmod 644 "$i"
+		fi
 	done
 
 	# copy default start.conf
@@ -219,21 +217,25 @@ create_linbofs() {
 	exec_hooks pre
 
 	# pack linbofs64.lz
-	echo "Creating lzma archive (may take a while) ..."
+	echo "Creating xz archive (may take a while) ..."
 	set -o pipefail
-	find . | cpio --quiet -o -H newc | lzma --threads=0 -zcv > "$linbofs_lz" ; RC="$?"
+	find . -print | cpio --quiet -o -H newc | xz -e --check=none -z -f -9 -c -v > "$linbofs_xz" ; RC="$?"
 	set +o pipefail
   	[ $RC -ne 0 ] && bailout "failed!"
 
 	# create md5sum file
-	md5sum "$linbofs_lz"  | awk '{ print $1 }' > "$linbofs_md5"
+	md5sum "$linbofs_xz"  | awk '{ print $1 }' > "$linbofs_md5"
+
+	# link to old filename
+	linbofs_lz="${linbofs_xz}.lz"
+	rm -f "${linbofs_lz}"*
+	ln -s "$(basename $linbofs_xz)" "$linbofs_lz"
+	ln -s "$(basename $linbofs_md5)" "${linbofs_lz}.md5"
 
 	# copy kernel image
 	echo "Copying $KTYPE kernel version $KVERS ..."
 	cp "$KERNELPATH" "$LINBODIR/linbo64"
 	md5sum "$LINBODIR/linbo64" | awk '{ print $1 }' > "$LINBODIR/linbo64.md5"
-
-	cd "$curdir"
 
 	echo "Ok!"
 }
@@ -256,7 +258,6 @@ else
 	exit 1
 fi
 
-# create new linbo filesystem
 create_linbofs
 
 # create iso files
